services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: DatabasePassword
    volumes:
      - postgresql_vol:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready --username=postgres && psql --username=postgres --list"
      timeout: 10s
      retries: 20 

  jira:
    image: atlassian/jira-software:latest
    volumes:
      - jira_postgresql_vol:/var/atlassian/application-data/jira 
    ports:
      - 8060:8080
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgresql_vol:
  jira_postgresql_vol: