services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: DatabasePassword
    volumes:
      - postgresql_vol:/var/lib/postgresql/data  

  jira:
    image: atlassian/jira-software:latest
    volumes:
      - jira_postgresql_vol:/var/atlassian/application-data/jira 
    ports:
      - 8060:8080
    depends_on:
      - db

volumes:
  postgresql_vol:
  jira_postgresql_vol: